services:
  prefixtree-service-a:
    build:
      context: .
      dockerfile: PrefixTreeServiceA/Dockerfile
    container_name: prefixtree-service-a
    ports:
      - "8080:8080"
    networks:
      - app-network

  prefixtree-service-b:
    build:
      context: .
      dockerfile: PrefixTreeServiceB/Dockerfile
    container_name: prefixtree-service-b
    depends_on:
      - prefixtree-service-a
    ports:
      - "8082:8080"
    networks:
      - app-network

  word-ingestor:
    build:
      context: ./IngestorService
      dockerfile: Dockerfile
    container_name: word-ingestor
    depends_on:
      - prefixtree-service-b
    environment:
      - REGION=local
    ports:
      - "8083:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
