#local 
#@PrefixTreeServiceA_HostAddress = http://localhost:5110
#Azure direct
@PrefixTreeServiceA_HostAddress = https://prefixtree-service-a.whitesmoke-63fac5e0.westus.azurecontainerapps.io
#Azure via APIM
#@PrefixTreeServiceA_HostAddress = https://dwc-apim.azure-api.net/prefixtree


# @requestTimeout=60000

### Insert a word into the Prefix Tree
POST {{PrefixTreeServiceA_HostAddress}}/api/words/insert?word=example
Accept: application/json

###


### Remove a word from the Prefix Tree
DELETE {{PrefixTreeServiceA_HostAddress}}/api/words/remove?word=example
Accept: application/json

###

### Search for a word in the Prefix Tree
GET {{PrefixTreeServiceA_HostAddress}}/api/words/search?word=example
Accept: application/json

###

### Get words with a specific prefix
GET {{PrefixTreeServiceA_HostAddress}}/api/words/autocomplete?prefix=el
Accept: application/json
