#local 
#@WordIngestorService_HostAddress = http://localhost:5110
#Azure direct
@WordIngestorService_HostAddress = https://word-ingestor.whitesmoke-63fac5e0.westus.azurecontainerapps.io
#Azure via APIM
#@WordIngestorService_HostAddress = http://localhost:5110

@requestTimeout=60000

### Provision the database and container in CosmosDB
POST {{WordIngestorService_HostAddress}}/api/words-ingestor/provision
Accept: application/json

###

### Initialize the WordsDB by wiping it and repopulating from words.txt
POST {{WordIngestorService_HostAddress}}/api/words-ingestor/initialize
Accept: application/json

###

### Load all words into the PrefixTree
POST {{WordIngestorService_HostAddress}}/api/words-ingestor/startup
Accept: application/json

###

### Add a batch of words to WordsDB and PrefixTree
POST {{WordIngestorService_HostAddress}}/api/words-ingestor/batch-add
Content-Type: application/json
Accept: application/json

[
    "example",
    "word",
    "test"
]

###

### Remove a batch of words from WordsDB and PrefixTree
DELETE {{WordIngestorService_HostAddress}}/api/words-ingestor/batch-delete
Content-Type: application/json
Accept: application/json

[
    "example",
    "word",
    "test"
]

###

### Start synchronization to listen for changes in WordsDB
POST {{WordIngestorService_HostAddress}}/api/words-ingestor/sync
Accept: application/json
